### ISSUE TITLE
Add support for detecting package manager when no lock file is present

### ISSUE THREAD

**Issue by MichaelDeBoey** [antfu-collective/package-manager-detector#19]
### Clear and concise description of the problem

In [remix-run/remix](https://github.com/remix-run/remix), we have our own implementation of `detectPackageManager`.
Only difference is that we currently check the `npm_config_user_agent` to determine which package manager is used.
https://github.com/remix-run/remix/blob/8649f1a561ce5ea0bfba5ab862c0c94052f4a5c3/packages/remix-dev/cli/detectPackageManager.ts#L10-L23

We do this because people can create a new project with one of our so called ["Stacks"](https://remix.run/docs/en/main/guides/templates#stacks), which can potentially _**not**_ have a lock file.

We also have a custom implementation in each of our stacks for the commands that we use:
- https://github.com/remix-run/indie-stack/blob/e63be8d06c20f92ffbcf30d8c69bf34258f26483/remix.init/index.js#L24-L64
- https://github.com/remix-run/blues-stack/blob/b050c907bc2a2778c9b4d9437d89c7c4751194fb/remix.init/index.js#L24-L64
- https://github.com/remix-run/grunge-stack/blob/fcd4729a209963ae1dd912e2d2cf0fdcd8644849/remix.init/index.js#L11-L47

It would be awesome if we could get rid of the custom implementation and use `package-manager-detector` instead.

### Suggested solution

Make it possible to detect package manager using `npm_config_user_agent`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by benmccann** [comment]
Yeah, we do this a few places too. I'd recommend we have separate methods for detecting the currently running package manager and the installed package manager as sometimes these can actually differ. E.g. it's valid to run `npx` inside a pnpm project.

**Comment by MichaelDeBoey** [comment]
Now that I created #21, I'm not sure if using `npm_config_user_agent` would (always) be the correct thing to look at though 🤔
