### ISSUE TITLE
Add support for Deno as package manager

### ISSUE THREAD

**Issue by MichaelDeBoey** [antfu-collective/package-manager-detector#21]
### Clear and concise description of the problem

[Deno is now a package manager with `deno install`](https://deno.com/blog/v2.0#deno-is-now-a-package-manager-with-deno-install)

### Suggested solution

Update all public methods to be able to recognize Deno as well

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by benmccann** [comment]
We might also have to add extra support specifically for Deno in `getUserAgent` added in https://github.com/antfu-collective/package-manager-detector/pull/20 or try to implement support in Deno (https://github.com/denoland/deno/issues/25342)

**Comment by Malix-Labs** [comment]
@benmccann it has just been closed :tada:

**Comment by birkskyum** [comment]
In case it's helpful for you, if you don't see the agent. I've just looked at adding deno to the solidjs cli, and found the agent only show when deno executes a npm:package or a package.json script - [see here](https://github.com/denoland/deno/pull/26639#issuecomment-2452399818)
