### ISSUE TITLE
generate provenance statements on release

### ISSUE THREAD

**Issue by MichaelDeBoey** [antfu-collective/package-manager-detector#24]
### Clear and concise description of the problem

This will also add a new Provenance section + a verified badge next to the version (in the sidebar + versions tab) to the NPM page

More info can be found at https://docs.npmjs.com/generating-provenance-statements

### Suggested solution

N/A

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by benmccann** [comment]
@antfu @userquin do you have a way you've set this up on your projects in the past?

I have it setup on Svelte/SvelteKit with `changesets` and would be happy to do that here, but I don't know if you want to change your publishing workflow. It requires a changeset to be included with each PR and a bot installed into the repo to help remind you of that and then allows you to create a release with the click of a button and will keep a changelog file updated. Happy to share more about the setup or do it without changesets as well if you're familiar with another way that you'd like to set it up

**Comment by userquin** [comment]
Anthony and me don't use `changesets` in our repos, feel free to send a PR with it if it is easy to remove it, otherwise I suggest you to send the PR without it.
