### ISSUE TITLE
inconsistency on projects with --no-lockfile

### ISSUE THREAD

**Issue by fernandolguevara** [antfu-collective/package-manager-detector#9]
This line is resolving PM wrongly as it first assumes that projects contain lockfile

https://github.com/antfu-collective/package-manager-detector/blob/2c335cd32dbacc01e89216e9eda40b13e616b942/src/index.ts#L25

**Comment by benmccann** [comment]
Can you provide more details? Does it crash or just provide wrong answer? What's happening vs what do you expect to happen?

**Comment by fernandolguevara** [comment]
After a short debugging I think the issue is that the working folder does not contain the lockfile and when using the findUp function it ends up resolving the package manager from parent directories which in my case is not related to the current project.

**Comment by benmccann** [comment]
I'm not sure this is a bug. What would you expect to happen instead?

At least for some package managers like pnpm, the lockfile is contained in an ancestor directory. What package manager are you using?

**Comment by fernandolguevara** [comment]
@benmccann I would expect this library to first exhausted all the strategies (lockfile, packageManager field on package.json) on the working directory and if no luck find on parent directories...
